### ISSUE TITLE
Social media button links mixed up

### ISSUE THREAD

**Issue by glynhudson** [jivemonkey2000/evhighwaystatus#1]
Loving the fact your now open-source, nice work :+1: 

Jut noticed that the social media button links are mixed up e.g. twitter button goes to FB and G+ icon goes to twitter! Facebook icon does nothing. Same on Chrome on Firefox.

**Comment by jivemonkey2000** [comment]
Good spot!

**Comment by jivemonkey2000** [comment]
Now fixed.
